import type { AppCategory } from './smart-transaction-categorizer.js';

/** Regras ordenadas da mais específica para a mais genérica. */
export const MERCHANT_CATEGORY_RULES: Array<{
  pattern: string;
  category: AppCategory;
}> = [
  { pattern: 'MERCADO LIVRE', category: 'Lazer' },
  { pattern: 'MERCADOLIVRE', category: 'Lazer' },
  { pattern: 'MERCADO PAGO', category: 'Transferências' },
  { pattern: 'MERCADOPAGO', category: 'Transferências' },
  { pattern: 'UBER EATS', category: 'Alimentação' },
  { pattern: 'UBEREATS', category: 'Alimentação' },
  { pattern: '99 FOOD', category: 'Alimentação' },
  { pattern: '99FOOD', category: 'Alimentação' },
  { pattern: 'RAPPI', category: 'Alimentação' },
  { pattern: 'IFOOD', category: 'Alimentação' },
  { pattern: 'ZDELIVERY', category: 'Alimentação' },
  { pattern: 'UBER TRIP', category: 'Transporte' },
  { pattern: 'UBER DO BRASIL', category: 'Transporte' },
  { pattern: 'UBER ', category: 'Transporte' },
  { pattern: 'UBER', category: 'Transporte' },
  { pattern: '99POP', category: 'Transporte' },
  { pattern: '99 POP', category: 'Transporte' },
  { pattern: '99APP', category: 'Transporte' },
  { pattern: '99 TAXI', category: 'Transporte' },
  { pattern: 'CABIFY', category: 'Transporte' },
  { pattern: 'INDRIVE', category: 'Transporte' },
  { pattern: 'DROGA RAIA', category: 'Saúde' },
  { pattern: 'DROGARAIA', category: 'Saúde' },
  { pattern: 'DROGASIL', category: 'Saúde' },
  { pattern: 'DROGARIA', category: 'Saúde' },
  { pattern: 'DROGA ', category: 'Saúde' },
  { pattern: 'FARMAC', category: 'Saúde' },
  { pattern: 'PACHECO', category: 'Saúde' },
  { pattern: 'PANVEL', category: 'Saúde' },
  { pattern: 'DROGAL', category: 'Saúde' },
  { pattern: 'SAO JOAO', category: 'Saúde' },
  { pattern: 'PAO DE ACUCAR', category: 'Alimentação' },
  { pattern: 'PAO DE AÇUCAR', category: 'Alimentação' },
  { pattern: 'CARREFOUR', category: 'Alimentação' },
  { pattern: 'ATACADAO', category: 'Alimentação' },
  { pattern: 'ASSAI', category: 'Alimentação' },
  { pattern: 'SUPERMERC', category: 'Alimentação' },
  { pattern: 'HAVAN', category: 'Lazer' },
  { pattern: 'SHOPEE', category: 'Lazer' },
  { pattern: 'SHEIN', category: 'Lazer' },
  { pattern: 'AMAZON', category: 'Lazer' },
  { pattern: 'MAGALU', category: 'Lazer' },
  { pattern: 'MAGAZINE LUIZA', category: 'Lazer' },
  { pattern: 'AMERICANAS', category: 'Lazer' },
  { pattern: 'NETSHOES', category: 'Lazer' },
  { pattern: 'CENTAURO', category: 'Lazer' },
  { pattern: 'DECATHLON', category: 'Lazer' },
  { pattern: 'NETFLIX', category: 'Assinaturas' },
  { pattern: 'SPOTIFY', category: 'Assinaturas' },
  { pattern: 'DISNEY', category: 'Assinaturas' },
  { pattern: 'HBO', category: 'Assinaturas' },
  { pattern: 'OPENAI', category: 'Assinaturas' },
  { pattern: 'CHATGPT', category: 'Assinaturas' },
  { pattern: 'SHELL', category: 'Transporte' },
  { pattern: 'IPIRANGA', category: 'Transporte' },
  { pattern: 'POSTO', category: 'Transporte' },
  { pattern: 'AUTO POSTO', category: 'Transporte' },
  { pattern: 'GASOLINA', category: 'Transporte' },
  { pattern: 'COMBUSTIV', category: 'Transporte' },
  { pattern: 'ESTACION', category: 'Transporte' },
  { pattern: 'PEDAGIO', category: 'Transporte' },
  { pattern: 'METRO', category: 'Transporte' },
  { pattern: 'MERCADO ', category: 'Alimentação' },
  { pattern: 'MINI MERCADO', category: 'Alimentação' },
  { pattern: 'RESTAUR', category: 'Alimentação' },
  { pattern: 'LANCH', category: 'Alimentação' },
  { pattern: 'PADARIA', category: 'Alimentação' },
  { pattern: 'PAGTO FAT', category: 'Transferências' },
  { pattern: 'PAGAMENTO FAT', category: 'Transferências' },
  { pattern: 'FATURA CART', category: 'Transferências' },
  { pattern: 'CREDITO CONTA', category: 'Transferências' },
  { pattern: 'DEBITO CONTA', category: 'Transferências' },
  { pattern: 'TRANSFERENCIA ENVIADA', category: 'Transferências' },
  { pattern: 'TRANSFERENCIA ENV', category: 'Transferências' },
  { pattern: 'TRANSFERENCIA PIX', category: 'Transferências' },
  { pattern: 'TRANSF ENVIADA', category: 'Transferências' },
  { pattern: 'TRANSF ENV', category: 'Transferências' },
  { pattern: 'TRANSF PIX', category: 'Transferências' },
  { pattern: 'PIX ENVIADO', category: 'Transferências' },
  { pattern: 'PIX ENVI', category: 'Transferências' },
  { pattern: 'ENVIO PIX', category: 'Transferências' },
  { pattern: 'PIX PARA', category: 'Transferências' },
  { pattern: 'TRANSF ', category: 'Transferências' },
  { pattern: ' TED', category: 'Transferências' },
  { pattern: ' DOC', category: 'Transferências' },
  { pattern: 'PICPAY', category: 'Transferências' },
  { pattern: 'SALARIO', category: 'Renda' },
  { pattern: 'SALÁRIO', category: 'Renda' },
  { pattern: 'FOLHA PAG', category: 'Renda' },
];
